env:
  - GO111MODULE=on

before:
  hooks:
    - go mod tidy
    - make build

builds:
  - binary: soba
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm
      - arm64

archives:
  - id: default
    wrap_in_directory: true
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
#archives:
#  - replacements:
#      darwin: Darwin
#      linux: Linux
#      windows: Windows
#      386: i386
#      amd64: x86_64
#checksum:
#  name_template: 'checksums.txt'
#snapshot:
#  name_template: "{{ incpatch .Tag }}-next"
#changelog:
#  sort: asc
#  filters:
#    exclude:
#      - '^docs:'
#      - '^test:'
