# This is an example .goreleaser.yml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
    - go mod tidy
    - make
builds:
  - binary: soba
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm
      - arm64
archives:
  - id: default
    wrap_in_directory: true
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
#archives:
#  - replacements:
#      darwin: Darwin
#      linux: Linux
#      windows: Windows
#      386: i386
#      amd64: x86_64
#checksum:
#  name_template: 'checksums.txt'
#snapshot:
#  name_template: "{{ incpatch .Tag }}-next"
#changelog:
#  sort: asc
#  filters:
#    exclude:
#      - '^docs:'
#      - '^test:'
