version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.16
    steps:
      - checkout
      - run: cwd
      - run: mkdir /apps/backup
      - run: go test -v -p 1 -parallel 1 -failfast ./...