name: goreleaser

on:
  push:
    tags:
      - '*'

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      -
        name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16
      -
        name: Run GoReleaser
#        if: success() && startsWith(github.ref, 'refs/tags/')
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-and-push-docker-image:
    runs-on: ubuntu-latest
    name: Docker Build, Tag, Push

    steps:
    -
      name: Checkout
      uses: actions/checkout@v1
    -
      name: Docker Build & Push Action
      uses: mr-smithers-excellent/docker-build-push@v5.5
      with:
        image: soba/soba
        registry: ghcr.io
        dockerfile: docker/Dockerfile
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GH_PAT }}

#      name: Build, Tag, Push
#      uses: mattdavis0351/actions/docker-gpr@v1
#      with:
#        repo-token: ${{ secrets.GITHUB_TOKEN }}
#        dockerfile-location: docker/
#        image-name: soba


#      -
#        name: Docker Login
#        uses: docker/login-action@v1
#        with:
#          registry: ghcr.io
#          username: ${{ github.repository_owner }}
#          password: ${{ secrets.GH_PAT }}

#  Build-and-Push-Docker-Image:
#    runs-on: ubuntu-latest
#    name: Docker Build, Tag, Push
#
#    steps:
#    -
#      name: Checkout
#      uses: actions/checkout@v1
#    -
#      name: Build, Tag, Push
#      uses: mattdavis0351/actions/docker-gpr@v1
#      with:
#        repo-token: ${{ secrets.GITHUB_TOKEN }}
#        dockerfile-location: docker/
#        image-name: soba